{{/**
  The interface templates are stable, thus this file should be unchanged.
*/}}

{{/** Core API */}}
{{- include "api.workload.deployment" . -}}
{{- include "api.configuration.configmap" . -}}
{{- include "api.network.service" . -}}
{{- include "api.network.ingress" . -}}
{{- include "api.storage.persistence.volume" . -}}
{{- include "api.storage.persistence.claim" . -}}

{{/** RBAC */}}
{{- include "api.rbac.serviceAccount" . -}}
{{- include "api.rbac.role" . -}}
{{- include "api.rbac.clusterRole" . -}}
{{- include "api.rbac.roleBinding" . -}}
{{- include "api.rbac.clusterRoleBinding" . -}}

