{{- define "charts.base.serviceAccount" -}}
{{- if .Values.serviceAccount.create -}}
{{- $name := coalesce .Values.namespace.name .Release.Name "default" -}}
{{/*
  ServiceAccount
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{ .Values.serviceAccount.annotations }}
  {{- end }}
{{- end }}
---
{{- end -}}