exposure:
  type: ingress
  enabled: true
  ingress:
    web:
      hostname: leryn.top
      path: "/"
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
      secrets: []
    gateway:
      hostname: leryn.top
      path: "/api/(.*)"
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
        ingress.kubernetes.io/rewrite-target: "/$1"
      secrets: []

externalURL: https://leryn.top
internalTLS: false

persistence:
  enabled: true
  persistentVolumeClaim:
    message-attachement:
      storageClass: "local-storage"
      accessModes:
        - ReadWriteOnce
      capacity: 1Gi
      annotations: {}
      mountOptions: {}
      local:
        path: "/data/leryn/message-center/attachment"
application:
  gateway:
    # language: java
    image:
      name: "harbor.leryn.top/leryn/leryn-api-gateway"
      tag: "nightly"
    secrets:
      - gateway-db
    ports:
      - port: 8080
    configMaps:
      - name: application.yml
        conf: gateway/application.yml
        path: /opt/config
  auth-server:
    # language: java
    image:
      name: "harbor.leryn.top/leryn/leryn-cloud-api-gateway"
      tag: "nightly"
    secrets:
      - auth-server-db
    ports:
      - port: 8080
    configMaps:
      - name: application.yml
        conf: auth-server/application.yml
        path: /opt/config
  message-center:
    # language: java
    image:
      name: "harbor.leryn.top/leryn/leryn-message"
      tag: "nightly"
    secrets:
      - message-center-db
    ports:
      - port: 8080
    configMaps:
      - name: application.yml
        conf: message-center/application.yml
        path: /opt/config
    persistences:
      - name: message-attachement
        claim: message-attachement
        path: /mnt/message
  web:
    # language: nginx
    image:
      name: "harbor.leryn.top/leryn/overture"
      tag: "nightly"
    ports:
      - port: 80
    configMaps:
      - name: nginx.conf
        conf: web/nginx.conf
        path: /usr/share/nginx/html
