nameOverride: ""
fullnameOverride: ""

# Global
kubeVersion: ""

# Kubernetes cluster domain.
clusterDomain: cluster.local

# Common annotations marked on all the resources rendered through charts. It would be overwritten if extra annotations
# are specified with the same key.
# (*) Default: {}
commonAnnotations: {}

# Namespace
# Create if `namespace.create` is true.
# .Release.Namespace => .Values.namespace.name => "default"
namespace:
  #
  # (*) Default: false
  create: false
  # Name of namespace if created.
  # (*) Default: ""
  name: ""

serviceAccount:
  create: false
  name: ""
  annotations: {}

exposure:
  enabled: false
  # Optional type to export the service.
  # (*) Enum:
  #   - ingress (*)
  #   - clusterIP
  #   - nodePort
  #   - loadBalancer
  type: nodePort
  ingress:
    controller: default
    # Omitted if null.
    # (*) Recommend: "nginx"
    class: "nginx"
    # Hostname
    # (*) Required
    hostname: "api.domain.com"
    # Ingress controller annotations
    # (*) Default: {}
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
    # Enable TLS for the host at `exposure.ingress.hostname`.
    # (*) Default: false
    tls: false
    # Enable self-signed TLS certificate if `exposure.ingress.tls` is enabled.
    # (*) Default: false
    selfSigned: false
    # Secret:
    # Custom TLS certificates as secrets.
    # Secret must contain TLS key and certificate.
    # (*) Default: []
    secret: []
  clusterIP:
  # TODO
  nodePort:
  # TODO
  loadBalancer:
  # TODO

externalURL: https://api.domain.com
internalTLS: false

ipFamily:
  ipv4:
    enabled: true
  ipv6:
    enabled: true

persistence:
  enabled: true
  persistentVolumeClaim:
    # TODO
    backend:
      existingClaim: ""
      storageClass: ""
      subPath: "."
      accessMode: ReadWriteOnce
      size: 1Gi
      annotations: {}

application:
  backend:
    image:
      # (*) Required.
      name: "docker.io/hello-world"
      # Docker image tag
      # (*) Default: "latest"
      tag: "latest"
    # (*) Default: []
    secrets: []
    # (*) Default: []
    ports:
      - # (*) Default: port-<port>
        name: http
        # Exposed container port.
        port: 8080
        # Exposed service port.
        # (*) Default: 80
        servicePort: 80
        # Protocol for specified container port.
        # (*) Default: TCP
        # enum:
        #   - TCP
        #   - UDP
        protocol: TCP

middlewares:
  redis:
  # TODO
  elasticsearch:
  # TODO
  kafka:
  # TODO
  mysql:
  # TODO
