
serviceAccount:
  create: false
  annotations: {}
  name: ""

namespace:
  create: false
  name: ""

# Composition of Deployment + Service
channels:
  web:
    services:
      frontend:
        replicas: 2
        container:
          repo: harbor.leryn.top/leryn/overture
          tag: nightly
          port: 80
    ingress:
      routes:
        host: leryn.top
        paths:
          - path: /
            service:
              name: frontend
        attributes:
          ingressClass: nginx
          sslRedirect: "false"
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 1G
  cloud:
    services:
      api-gateway:
        container:
          repo: harbor.leryn.top/leryn/leryn-api-gateway
          port: 8080
        configMaps:
          - name: config
            filename: application.yaml
            mountPath: /opt/config/
            values: |-
              server:
                port: 8080
        env:
          DB_USERNAME: scott
          DB_PASSWORD: 907BR1jQ05P3hxBu
          DB_URL: "jdbc:mysql://121.196.30.39:3306/gateway?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
      auth-server:
        replicas: 1
        container:
          repo: harbor.leryn.top/leryn/leryn-auth-server
          port: 8080
        env:
          DB_USERNAME: scott
          DB_PASSWORD: 907BR1jQ05P3hxBu
          DB_URL: "jdbc:mysql://121.196.30.39:3306/idaas?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
      message-center:
        replicas: 1
        container:
          repo: harbor.leryn.top/leryn/leryn-message
          port: 8080
        env:
          DB_USERNAME: scott
          DB_PASSWORD: 907BR1jQ05P3hxBu
          DB_URL: "jdbc:mysql://121.196.30.39:3306/message?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
    ingress:
      routes:
        host: leryn.top
        paths:
          - path: /api/(.*)
            service:
              name: api-gateway
        attributes:
          ingressClass: nginx
          sslRedirect: "false"
          rewriteTarget: /$1
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 1G
