---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oss-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - leryn-aliyun01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-data-pvc
  namespace: oss
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  volumeName: oss-data-pv