apiVersion: v1
kind: ServiceAccount
metadata:
  name: oss
  namespace: oss
---
apiVersion: v1
kind: Service
metadata:
  name: oss-web-server
  labels:
    app.kubernetes.io/name: oss
    app.kubernetes.io/instance: oss-web-server
spec:
  selector:
    app.kubernetes.io/name: oss
    app.kubernetes.io/instance: oss-web-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: oss-web-adm
  labels:
    app.kubernetes.io/name: oss
    app.kubernetes.io/instance: oss-web-adm
spec:
  selector:
    app.kubernetes.io/name: oss
    app.kubernetes.io/instance: oss-web-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss-web-server
  labels:
    app.kubernetes.io/name: oss
    app.kubernetes.io/instance: oss-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oss
      app.kubernetes.io/instance: oss-web-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oss
        app.kubernetes.io/instance: oss-web-server
    spec:
      serviceAccountName: oss
      containers:
        - name: oss-web-server
          image: "minio/minio:latest"
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 9000
            - protocol: TCP
              containerPort: 9001
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          envFrom:
            - secretRef:
                name: oss-config
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 50m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 9001
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          volumeMounts:
            - name: oss-data-volume
              mountPath: /data
            - name: oss-conf-volume
              mountPath: /root/.minio
      volumes:
        - name: oss-data-volume
          persistentVolumeClaim:
            claimName: oss-data-pvc
        - name: oss-conf-volume
          persistentVolumeClaim:
            claimName: oss-conf-pvc
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - oss
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - oss-web-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oss-web-server
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app.kubernetes.io/name: oss
    app.kubernetes.io/instance: oss-web-server
spec:
  rules:
    - host: oss.leryn.top
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: oss-web-server
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oss-web-adm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app.kubernetes.io/name: oss
    app.kubernetes.io/instance: oss-web-adm
spec:
  rules:
    - host: oss-adm.leryn.top
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: oss-web-adm
                port:
                  number: 80
