apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea
  namespace: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-server
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea-server
spec:
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-server
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
      app.kubernetes.io/instance: gitea-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitea
        app.kubernetes.io/instance: gitea-server
    spec:
      serviceAccountName: gitea
      containers:
        - name: gitea-server
          image: "docker.io/gitea/gitea:latest"
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 22
            - protocol: TCP
              containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 50m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          volumeMounts:
            - name: gitea-data-volume
              mountPath: /data
      volumes:
        - name: gitea-data-volume
          persistentVolumeClaim:
            claimName: gitea-data-pvc
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - gitea
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - gitea-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-server
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET,POST,PUT,DELETE,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea-server
spec:
  rules:
    - host: gitea.leryn.top
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: gitea-server
                port:
                  number: 80
  tls:
    - hosts:
        - drone.leryn.top
      secretName: leryn.top
